.PHONY:clean all
CC=gcc
CFLAGS=-Wall -g
BIN=tinyftpd
OBJS= main.o commsocket.o sckutil.o session.o ftpproto.o \
privparent.o str.o tunable.o parseconf.o privsock.o hash.o
LIBS=-lcrypt
$(BIN):$(OBJS)
	$(CC) $(CFLAGS) $^ -o $@ $(LIBS)
	
%.o:%.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f *.o $(BIN)



